### ISSUE TITLE
Rethrowing exception

### ISSUE THREAD

**Issue by zkoppert** [tektronix/initialstate.NET#10]
Issue: https://lgtm.com/projects/g/tektronix/initialstate.NET/alerts/?mode=tree&ruleFocus=1506093616210

For Details on how to fix: https://lgtm.com/rules/1506093616210/

**Comment by B1tF8er** [comment]
I can take this @zkoppert but I would like to make the PR until October, is that ok?

**Comment by zkoppert** [comment]
@B1tF8er No problem.

**Comment by zkoppert** [comment]
@B1tF8er Hey, Looks like somebody already submitted a fix for this. Perhaps this issue would work for you instead? #12

**Comment by dwyban** [comment]
Cleaned up in 2707c3d2ddc0474aea1bcbc0aa793c7fc26b01ab
