### ISSUE TITLE
Useless Variable

### ISSUE THREAD

**Issue by zkoppert** [tektronix/initialstate.NET#12]
Issue:
    https://lgtm.com/projects/g/tektronix/initialstate.NET/rev/pr-99f9a067e90de6730d9f8eaeff4b087c9d20ba78

How to Fix:
    https://lgtm.com/rules/1506093386171/

**Comment by zkoppert** [comment]
@B1tF8er How about this issue?

**Comment by B1tF8er** [comment]
@zkoppert yeah I can take it
