### ISSUE TITLE
Make initialstate.NET available as a NuGet package

### ISSUE THREAD

**Issue by dwyban** [tektronix/initialstate.NET#18]
Probably the simplest way to integrate third party libraries like this one into your project is to use the NuGet package manager (if a NuGet package is available).  initialstate.NET needs a NuGet package.

**Comment by atrievel** [comment]
Hey @dwyban, I'd like to take this on if no one else is yet!

**Comment by atrievel** [comment]
@dwyban I'll need to know a licence URL, project URL, icon URL, and some tags for the package otherwise they will be left blank

**Comment by atrievel** [comment]
@dwyban I'll also need to know your organization's NuGet API key in order to publish this. If you do not feel comfortable doing this, I can provide everything you'll need and the documentation on how to get the package publish. It takes 5 minutes if that when you have the API key

**Comment by dwyban** [comment]
Let me consult with our open source office and get back to you.

**Comment by dwyban** [comment]
Hi @atrievel.  I'm still learning about how to go about creating a NuGet package for this project and after talking with our OpenSource office I think due to account security reasons we're going to have to handle this one internally.  Thank you for offering to help though.

**Comment by atrievel** [comment]
No worries @dwyban! Here’s some helpful [documentation](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package) to get you guys started. It’s not too complicated of a process. Best of luck 👍

**Comment by dwyban** [comment]
Looks like I was able to get it published under my own account so this is working.
https://www.nuget.org/packages/InitialState.NET/

Will need to remove and get it published under Tek's account.
